config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  
  resources :traveller_groups do 
    resources :travellers
  end
  
  resources :guides
  
  resources :agencies do 
    resources :agency_contacts
  end

  resources :trips
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/traveller_group.rb
class TravellerGroup < ActiveRecord::Base
  belongs_to :trip
  belongs_to :agency_contact
  has_many :travellers
end

app/controllers/traveller_groups_controller.rb
class TravellerGroupsController < ApplicationController
  before_action :set_traveller_group, only: [:show, :edit, :update, :destroy]

  # GET /traveller_groups
  # GET /traveller_groups.json
  def index
    @traveller_groups = TravellerGroup.all
  end

  # GET /traveller_groups/1
  # GET /traveller_groups/1.json
  def show
    
  end

  # GET /traveller_groups/new
  def new
    @traveller_group = TravellerGroup.new
  end

  # GET /traveller_groups/1/edit
  def edit
  end

  # POST /traveller_groups
  # POST /traveller_groups.json
  def create
    @traveller_group = TravellerGroup.new(traveller_group_params)

    respond_to do |format|
      if @traveller_group.save
        format.html { redirect_to @traveller_group, notice: 'Traveller group was successfully created.' }
        format.json { render :show, status: :created, location: @traveller_group }
      else
        format.html { render :new }
        format.json { render json: @traveller_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traveller_groups/1
  # PATCH/PUT /traveller_groups/1.json
  def update
    respond_to do |format|
      if @traveller_group.update(traveller_group_params)
        format.html { redirect_to @traveller_group, notice: 'Traveller group was successfully updated.' }
        format.json { render :show, status: :ok, location: @traveller_group }
      else
        format.html { render :edit }
        format.json { render json: @traveller_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traveller_groups/1
  # DELETE /traveller_groups/1.json
  def destroy
    @traveller_group.destroy
    respond_to do |format|
      format.html { redirect_to traveller_groups_url, notice: 'Traveller group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traveller_group
      @traveller_group = TravellerGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traveller_group_params
      params.require(:traveller_group).permit(:trip_id, :agency_contact_id, :trav_date, :price_receivable, :price_received, :price_for_sb)
    end
end

app/helpers/traveller_groups_helper.rb
module TravellerGroupsHelper
end

app/views/traveller_groups/_form.html.erb
<!-- Form starts -->
<div class="awidget">
   <div class="awidget-head">
      <h3>游客小组</h3>
   </div>
   <div class="awidget-body">
       
<%= simple_form_for(@traveller_group, html: {class: 'form-inline'}) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-inputs mb-10">
        <%= f.association :trip %>
      </div>
      <div class="form-inputs mb-10">
        <%= f.association :agency_contact %>
      </div>
      <div class="form-inputs mb-10">
        <%= f.input :trav_date %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-inputs mb-10">
        <%= f.input :price_receivable %>
      </div>
      <div class="form-inputs mb-10">
        <%= f.input :price_received %>
      </div>
      <div class="form-inputs mb-10">
        <%= f.input :price_for_sb %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-inputs mb-10">
        <div class="form-group decimal optional traveller_group_price_need_recieve">
          <label class="decimal optional control-label" for="price_need_recieve">未收</label>
          <input class="numeric decimal optional form-control" type="number" step="any" value="" name="price_need_recieve" id="price_need_recieve">
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  </div>
<% end %>

   </div>
</div>
<!-- Form ends -->    

app/views/traveller_groups/_travellers.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>编号</th>
      <th>姓名</th>
      <th>电话</th>
      <th>证件号码</th>
      <th>是否小孩</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traveller_group.travellers.each do |traveller| %>
      <tr>
        <td><%= traveller.id %></td>
        <td><%= traveller.name %></td>
        <td><%= traveller.mobile %></td>
        <td><%= traveller.id_card %></td>
        <td><%= traveller.is_kid %></td>
        <td><%= link_to '修改', edit_traveller_group_traveller_path(@traveller_group, traveller) %></td>
        <td><%= link_to '删除', traveller_group_traveller_path(@traveller_group, traveller), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/traveller_groups/edit.html.erb
<h1>旅客小组</h1>

<%= render 'form' %>
<hr/>
<h2>小组成员</h2>
<%= render 'travellers' %>

app/views/traveller_groups/index.html.erb
<div class="header-title">
  <div class="row">
    <div class="col-md-6">
      <h1>游客小组</h1>
    </div>
    <div class="col-md-6 text-right">
      <%= link_to '添加小组', new_traveller_group_path, class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
</div>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>旅游线路</th>
      <th>组团社联系人</th>
      <th>出游日期</th>
      <th>应收款</th>
      <th>已收款</th>
      <th>代收款</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @traveller_groups.each do |traveller_group| %>
      <tr>
        <td><%= traveller_group.trip.name %></td>
        <td><%= traveller_group.agency_contact.try(:name) %></td>
        <td><%= traveller_group.trav_date %></td>
        <td><%= traveller_group.price_receivable %></td>
        <td><%= traveller_group.price_received %></td>
        <td><%= traveller_group.price_for_sb %></td>
        <td>
          <%= link_to '上传凭证', '#' %> | 
          <%= link_to '修改', edit_traveller_group_path(traveller_group) %> ｜ 
          <%= link_to '删除', traveller_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/traveller_groups/new.html.erb
<h1>添加旅游小组</h1>

<%= render 'form' %>

<%= link_to '返回', traveller_groups_path %>

app/views/traveller_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip:</strong>
  <%= @traveller_group.trip %>
</p>

<p>
  <strong>Agency contact:</strong>
  <%= @traveller_group.agency_contact %>
</p>

<p>
  <strong>Trav date:</strong>
  <%= @traveller_group.trav_date %>
</p>

<p>
  <strong>Price receivable:</strong>
  <%= @traveller_group.price_receivable %>
</p>

<p>
  <strong>Price received:</strong>
  <%= @traveller_group.price_received %>
</p>

<p>
  <strong>Price for sb:</strong>
  <%= @traveller_group.price_for_sb %>
</p>

<%= link_to 'Edit', edit_traveller_group_path(@traveller_group) %> |
<%= link_to 'Back', traveller_groups_path %>