config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  
  resources :traveller_groups do 
    resources :travellers
  end
  
  resources :guides
  
  resources :agencies do 
    resources :agency_contacts
  end

  resources :trips
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :agency_contacts
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    @agency.en_name = Pinyin.t(@agency.name)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to agencies_path, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to agencies_path, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :en_name, :address)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<!-- Form starts -->
<div class="awidget">
   <div class="awidget-head">
      <h3>组团社</h3>
   </div>
   <div class="awidget-body">
       
<%= simple_form_for(@agency) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

   </div>
</div>
<!-- Form ends -->    

app/views/agencies/edit.html.erb
<%= render 'form' %>

<%= link_to '返回', agency_path(@agency) %>

app/views/agencies/index.html.erb
<div class="header-title">
  <div class="row">
    <div class="col-md-6">
      <h1>组团社</h1>
    </div>
    <div class="col-md-6 text-right">
      <%= link_to '添加组团社', new_agency_path, class: 'btn btn-primary btn-lg'  %>
    </div>
  </div>
</div>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>编号</th>
      <th>名称</th>
      <th>地址</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.id %></td>
        <td><%= agency.name %></td>
        <td><%= agency.address %></td>
        <td><%= link_to new_agency_agency_contact_path(agency), class: 'btn btn-info' do %>
            <i class="fa fa-user"></i> 添加联系人
          <% end %>
        </td>
        <td>
          <%= link_to '查看', agency %>｜
          <%= link_to '修改', edit_agency_path(agency) %>｜
          <%= link_to '删除', agency, method: :delete, data: { confirm: '确定要删除吗?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agencies/new.html.erb
<h1>添加组团社</h1>

<%= render 'form' %>

<%= link_to '返回', agencies_path %>

app/views/agencies/show.html.erb
<%= render partial: 'layouts/breadcrumb', locals: {title: @agency.name, urls: [['修改', edit_agency_path(@agency)], ['返回', agencies_path]]} %>

<h2>
  <%= @agency.name %>
  <small><%= @agency.address %></small>
</h2>

<h3>联系人</h3>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>姓名</th>
      <th>电话</th>
      <th>联系人</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agency.agency_contacts.each do |agency_contact| %>
      <tr>
        <td><%= agency_contact.name %></td>
        <td><%= agency_contact.mobile %></td>
        <td><%= agency_contact.is_admin ? '是' : '' %></td>
        <td><%= link_to '修改', edit_agency_agency_contact_path(@agency, agency_contact) %> | 
          <%= link_to '删除', agency_agency_contact_url(@agency, agency_contact), method: :delete, data: { confirm: '确定删除?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>