config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  
  resources :traveller_groups do 
    resources :travellers
  end
  
  resources :guides
  
  resources :agencies do 
    resources :agency_contacts
  end

  resources :trips
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/agency_contact.rb
class AgencyContact < ActiveRecord::Base
  belongs_to :agency
end

app/controllers/agency_contacts_controller.rb
class AgencyContactsController < ApplicationController
  before_action :set_agency
  before_action :set_agency_contact, only: [:show, :edit, :update, :destroy]

  # GET /agency_contacts
  # GET /agency_contacts.json
  def index
    @agency_contacts = AgencyContact.all
  end

  # GET /agency_contacts/1
  # GET /agency_contacts/1.json
  def show
  end

  # GET /agency_contacts/new
  def new
    @agency_contact = AgencyContact.new
  end

  # GET /agency_contacts/1/edit
  def edit
  end

  # POST /agency_contacts
  # POST /agency_contacts.json
  def create
    @agency_contact = AgencyContact.new(agency_contact_params)

    respond_to do |format|
      if @agency_contact.save
        format.html { redirect_to @agency, notice: 'Agency contact was successfully created.' }
        format.json { render :show, status: :created, location: @agency_contact }
      else
        format.html { render :new }
        format.json { render json: @agency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agency_contacts/1
  # PATCH/PUT /agency_contacts/1.json
  def update
    respond_to do |format|
      if @agency_contact.update(agency_contact_params)
        format.html { redirect_to @agency, notice: 'Agency contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency_contact }
      else
        format.html { render :edit }
        format.json { render json: @agency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agency_contacts/1
  # DELETE /agency_contacts/1.json
  def destroy
    @agency_contact.destroy
    respond_to do |format|
      format.html { redirect_to agency_contacts_url, notice: 'Agency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:agency_id])
    end

    def set_agency_contact
      @agency_contact = AgencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_contact_params
      params.require(:agency_contact).permit(:agency_id, :name, :mobile, :is_admin)
    end
end

app/helpers/agency_contacts_helper.rb
module AgencyContactsHelper
end

app/views/agency_contacts/_form.html.erb
<!-- Form starts -->
<div class="awidget">
   <div class="awidget-head">
      <h3>组团社联系人</h3>
   </div>
   <div class="awidget-body">
       
<%= simple_form_for([@agency, @agency_contact]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%#= f.association :agency, selected: params[:agency_id] %>
    <%= f.input :agency_id, as: :hidden, input_html: { value: @agency.id} %>
    <%= f.input :name %>
    <%= f.input :mobile %>
    <%= f.input :is_admin, input_html: { checked: @agency.agency_contacts.any? ? false : true} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

   </div>
</div>
<!-- Form ends -->    

app/views/agency_contacts/edit.html.erb
<h1>修改联系人信息</h1>

<%= render 'form' %>

app/views/agency_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>联系人</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Agency</th>
      <th>Name</th>
      <th>Mobile</th>
      <th>Is admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agency_contacts.each do |agency_contact| %>
      <tr>
        <td><%= agency_contact.agency %></td>
        <td><%= agency_contact.name %></td>
        <td><%= agency_contact.mobile %></td>
        <td><%= agency_contact.is_admin %></td>
        <td><%= link_to 'Show', agency_contact %></td>
        <td><%= link_to 'Edit', edit_agency_contact_path(agency_contact) %></td>
        <td><%= link_to 'Destroy', agency_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency contact', new_agency_contact_path %>

app/views/agency_contacts/new.html.erb
<h1>组团社：<small><%=@agency.name %></small></h1>

<%= render 'form' %>

<hr/>
<%= link_to '返回', agency_path(@agency) %>

app/views/agency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agency:</strong>
  <%= @agency_contact.agency %>
</p>

<p>
  <strong>Name:</strong>
  <%= @agency_contact.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @agency_contact.mobile %>
</p>

<p>
  <strong>Is admin:</strong>
  <%= @agency_contact.is_admin %>
</p>

<%= link_to 'Edit', edit_agency_contact_path(@agency_contact) %> |
<%= link_to 'Back', agency_contacts_path %>