config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  
  resources :traveller_groups do 
    resources :travellers
  end
  
  resources :guides
  
  resources :agencies do 
    resources :agency_contacts
  end

  resources :trips
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_breadcrumb.html.erb
<div class="row">
  <div class="col-md-12">
     <ol class="breadcrumb">
      <li><%= title %></li>
      <% urls.each do |url| %>
        <li><%= link_to url[0], url[1] %></li>
      <% end %>
    </ol>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to '修改密码', edit_user_registration_path %></li>
  <li><%= link_to '退出', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to '登录', new_user_session_path %></li>
  <li><%= link_to '注册', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to '用户管理', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">导航</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '首页', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to '关于', page_path('about') %></li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">初始化信息 <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to '旅游线路', trips_path %></li>
      <li><%= link_to '组团社', agencies_path %></li>
      <li><%= link_to '导游', guides_path %></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">游客管理 <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to '游客查询', traveller_groups_path %></li>
      <li><%= link_to '新增游客', new_traveller_group_path %></li>
    </ul>
  </li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "环景国旅OA" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "环景国旅OA" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' unless current_page?(root_path) %>
    </header>
    <% unless current_page?(root_path) %>
      <div style="margin-top: 40px;">&nbsp;</div>
    <% end %>
    <%= render 'layouts/messages' %>

    <% if current_page?(root_path) %>
      <%= yield %>  
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>